/**
  * THRONEMASTER.NET & GAME OF THRONES BROWSER GAME
  * -- default language resource (EN)
  *
  * (c) Copyright 2014
  * by JM Grip
  */
var STR = {
    // HOUSES
    HOUSE_B : "Baratheon",
    HOUSE_L : "Lannister",
    HOUSE_S : "Stark",
    HOUSE_T : "Tyrell",
    HOUSE_G : "Greyjoy",
    HOUSE_M : "Martell",
    HOUSE_U : "Tully",
    HOUSE_X : "Bolton",
    HOUSE_F : "Frey",
    HOUSE_A : "Arryn",
    HOUSE_Y : "Targaryen",
    // MISC
    PLAYER : "Player",
    OK : "OK",
    O_K : "O K",
    YES : "YES",
    NO : "NO",
    ON : "ON",
    OFF : "OFF",
    ONLINE : "online",
    OFFLINE : "offline",
    SUBMIT : "Submit",
    SEND : "Send",
    UPDATE : "Update",
    PROCEED : "Proceed",
    REVOKE : "Revoke",
    ORDER_ADVICE : "Order Advice",
    ORDER_OWNER : "Order Token of House {0}",
    MENU_RELOAD : "Reload Game",
    MENU_REVIEW : "Review Game",
    MENU_LOG : "Game Log",
    MENU_SOUND : "Sound",
    MENU_NOTES : "Game Notes",
    MENU_CHAT : "Chat Box",
    TRACK_THRONE : "Iron Throne",
    TRACK_FIEFDOMS : "Fiefdoms",
    TRACK_COURT : "King's Court",
    SPECTATOR : "SPECTATOR MODE",
    HOUSE_UNDEFINED : "<no house>",
    UNIT_FOOTMAN : "Footman",
    UNIT_FOOTMEN : "Footmen",
    UNIT_KNIGHT : "Knight",
    UNIT_KNIGHTS : "Knights",
    UNIT_SIEGE : "Siege Engine",
    UNIT_SIEGES : "Siege Engines",
    UNIT_SHIP : "Ship",
    UNIT_SHIPS : "Ships",
    UNIT_OWNER : "{0} Unit of House {1}",
    TURNS : "Turn {0} of {1}",
    WILDLINGS : "Wildling Strength",
    SPECIAL_TOKEN_THRONE : "Iron Throne",
    SPECIAL_TOKEN_BLADE : "Valyrian Steel Blade",
    SPECIAL_TOKEN_RAVEN : "Messenger Raven",
    NO_MAP_SUPPORT : "This function is not supported on this map yet.",
    BID_MISSING : "Bid phase: You have to set a number of power tokens first!",
    BID_ALREADY : "You already bid {0} power tokens!\nNo action necessary.",
    CHAT_INIT_FAILED : "Chat couldn't be initialized!",
    CHAT_NEW_TITLE : "New Chat Message",
    CHAT_PM : "You have {0} new whispered messages!",
    PHASE_TITLE_EVENTS : "The Westeros Phase",
    PHASE_TITLE_PLANNING : "The Planning Phase",
    PHASE_TITLE_ACTION : "The Action Phase",
    PHASE_ACTION_RAID : "Resolve Raid orders",
    PHASE_ACTION_MARCH : "Resolve March orders",
    PHASE_ACTION_CP : "Resolve Consolidate Power orders",
    PHASE_ACTION_BATTLE : "Resolving Battle",
    STATUS_WAITING : "Waiting for other players...",
    STATUS_WAITING_NAME : "Waiting for {0}...",
    STATUS_WAITING_THRONE : "Waiting for player with the Iron Throne...",
    ALRT_TURN : "It's your turn!",
    // DIALOGS TEXTS
    DLG_MAIN_WIN_TXT : "Conquer {0} cities to win!",
    DLG_MAIN_REVIEW_TXT : "Retrace players' movements",
    DLG_MAIN_AOF : "Areas Of Influence",
    DLG_MAIN_SUPPLY: "Supply",
    DLG_MAIN_STATUS: "Game State",
    DLG_MAIN_HOUSES: "Houses",
    DLG_MAIN_LADDER: "Leading Players",
    DLG_MAIN_SPEED: "Moves & Player Speed",
    DLG_MAIN_ACTION: "Recent Actions",
    DLG_MAIN_REVIEW: "GAME REVIEW",
    DLG_REVIEW_ROUND: "Round",
    DLG_REVIEW_WILDLINGS: "Wildlings",
    DLG_REVIEW_EVENT: "Event",
    DLG_MAIN_NFO_KNIGHT : "Unit: Knight ({0} Str)",
    DLG_MAIN_NFO_FOOTMEN : "Unit: Footman ({0} Str)",
    DLG_MAIN_NFO_SHIP : "Unit: Ship ({0} Str)",
    DLG_MAIN_NFO_CASTLE : "Stronghold: {0} Mustering Points",
    DLG_MAIN_NFO_CITY : "City: {0} Mustering Point",
    DLG_MAIN_USR_PROFILE : "Go to player's profile",
    DLG_MAIN_USR_WHISPER : "Whisper to {0}",
    DLG_MENU_BIDS : "Bid Result",
    DLG_MENU_BATTLE : "Battle Details",
    DLG_MUSTER_NO_POINTS : "You have no Mustering Points left.",
    DLG_SELECT_CARD : "House Card Selection",
    DLG_SELECT_CARD_NONE : "no cards available",
    DLG_MENU_SWITCH_TITLE : "Switch to PBEM mode!",
    DLG_SWITCH : "Switching to PBEM mode...",
    DLG_SWITCH_TITLE : "PLAY MODE CONTROL",
    DLG_NOTES_TITLE : "Personal Game Notes",
    DLG_SPECIAL_TOKEN_TITLE : "Choose Available Tokens",
    DLG_SPECIAL_TOKEN_REFUSE : "No, I don't want to!",
    DLG_BID_TITLE : "Your Bid",
    DLG_TIED_BIDS_TITLE : "Resolve Tied Bids",
    // ERROR MESSAGES
    ERR_AREA_OWNER : "ERROR: Invalid area owner {0} for {1}", // "Invalid area owner Baratheon for Lannisport"
    ERR_CONTACT : "Contact a game moderator!",
    ERR_ORDER_REMOVED : "UNEXPECTED ERROR: At least one of your orders has been removed!\nReload and try again.",
    ERR_ORDER_ATTACKER : "UNEXPECTED ERROR: Attacker's order token not removed!\nReload and try again.",
    ERR_NOTES_LOADING : "Error while loading game notes.",
    // TOOLTIPS
    TTIP_AREA_CTRL : "{0} controls this area.",
    TTIP_GARRISON : "Garrison of House {0} - Strength : {1}",
    TTIP_STATUS_POWER : "Power Tokens",
    TTIP_STATUS_POWER_A : "Available",
    TTIP_STATUS_POWER_U : "On Board",
    TTIP_STATUS_POWER_P : "In Pool",
    TTIP_NTRL_FORCES1 : "Neutral forces prevent a casual march into this area!",
    TTIP_NTRL_FORCES2 : "To march into this area, you must equal or exceed the neutral unit strength of {0}.",
    // WESTEROS PHASE
    EVT_DECK : "Deck", // card deck I-III
    EVT_SUB_WSTR : "{0} wildling str.",
    EVT_NO_INFO : "No card info availabe.",
    EVT_DONT_FORGET : "Do not forget",
    // DECK 1
    EVT_MUSTER : "Mustering",
    EVT_MUSTER_TTIP : "Players muster new units from their cities and strongholds.",
    EVT_MUSTER_STATUS : "Click on land or sea areas to recruit footmen or ship units. Select a footmen unit for upgrading to a knight. New units must conform to a player's Supply limits.",
    EVT_MUSTER_SUPPLY : "You already reached your Supply Limit.",
    EVT_MUSTER_NEW : "You're not able to muster new units here.",
    EVT_MUSTER_UP  : "You're not able to upgrade this unit.",
    EVT_MUSTER_LOW_SUPPLY : "Your Supply Level is too low.",
    EVT_MUSTER_NO_MP : "You have no more Mustering Points left for this area.",
    EVT_MUSTER_NOT_POSSIBLE : "no mustering possible",
    EVT_MUSTER_POINTS_USED : "Mustering Points used",
    EVT_MUSTER_NO_MP_SHIP : "You have no Mustering Points left to muster a ship here.",
    EVT_MUSTER_NO_KNIGHTS : "You don't have knight units anymore.",
    EVT_MUSTER_NO_FOOTMEN : "You don't have any footmen units anymore.",
    EVT_MUSTER_NO_SHIPS : "You don't have ship units anymore.",
    EVT_MUSTER_MAX_ARMY : "You have already reached your maximum army size.",
    EVT_MUSTER_MAX_FLEET : "You already reached the maximum fleet size.",
    EVT_SUPPLY : "Supply",
    EVT_SUPPLY_TTIP : "In Order of Play, players adjust their Supply token and reconcile their armies until they meet the supply limit.",
    EVT_SUPPLY_STATUS : "In Order of Play, players adjust their Supply token and reconcile their armies until they meet the supply limit.",
    EVT_SUPPLY_INFO : "Your new Supply Limit is too low.\nRemove units till your Supply is propper to your armies!\n\nTo remove an unit, click on its image.",
    EVT_SUPPLY_NEW : "Your new Supply Level is {0}!",
    EVT_SUPPLY_NOT_READY : "You haven't removed enough units yet!",
    EVT_SUPPLY_OK_ALREADY : "You already removed enough units.",
    EVT_SUPPLY_SINGLE_UNIT : "You cannot remove a supply independent unit!",
    EVT_WINTER : "Winter is Coming",
    EVT_WINTER_TTIP : "Immediately shuffle this Westeros deck and draw another card.",
    EVT_WINTER_STATUS : "Immediately shuffle this Westeros deck and draw another card.",
    EVT_SUMMER : "Last Days of Summer",
    EVT_SUMMER_TTIP : "Nothing happens.",
    EVT_SUMMER_STATUS : "Nothing happens.",
    // DECK 2
    EVT_THRONES : "Game of Thrones",
    EVT_THRONES_TTIP : "Each player collects one Power token from the Power Pool for every Crown Icon present in the areas that he controls.",
    EVT_THRONES_STATUS : "Each player collects one Power token from the Power Pool for every Crown Icon present in the areas that he controls.",
    EVT_CLASH : "Clash of Kings",
    EVT_CLASH_TTIP : "Players now bid available power for position on the Areas of Influence.",
    EVT_CLASH_STATUS : "Players now bid available power for position on the Areas of Influence. The player who currently controls the Iron Throne token may decide on tied bids.",
    EVT_CLASH_TIED : "This constellation is not possible!",
    EVT_CLASH_EMPTY_SLOTS : "Some Influence Positions are still empty!",
    EVT_CLASH_WAITING : "Waiting for resolving area...",
    // DECK 3
    EVT_WILDLINGS : "Wildling Attack",
    EVT_WILDLINGS_TTIP : "All players must bid power to bolster the Night's Watch.",
    EVT_WILDLINGS_STATUS : "The wildlings attack Westeros with the current strength of {0}. All players must bid power to bolster the Night's Watch.",
    EVT_WILDLINGS_LOST : "Night's Watch's defence was successful!<br>The player who bid the highest amount of power may take back any one of his used House Cards.",
    EVT_WILDLINGS_WIN : "The Wildlings were victorious!<br>Each player must remove 2 mustering points worth of units (Trooper/Ship = 1, Knight = 2). Click on unit image to remove the unit.",
    EVT_WILDLINGS_4MP : "Losing 4 Mustering Points instead of 2",
    EVT_WILDLINGS_RETURN_CARD : "Taking back one used House Card:",
    EVT_WILDLINGS_REMOVE_MP : "You have to remove {0} Mustering Points.\nHouse {1} was chosen to remove 4...",
    EVT_SWORDS : "Storm of Swords",
    EVT_SWORDS_TTIP : "Players may not place Defense order tokens during the Planning Phase of this turn.",
    // EVT_SWORDS_STATUS : "Players may not place Defense order tokens during the Planning Phase of this turn.",
    EVT_STORMS : "Sea of Storms",
    EVT_STORMS_TTIP : "Players may not place Raid order tokens during the Planning Phase of this turn.",
    // EVT_STORMS_STATUS : "Players may not place Raid order tokens during the Planning Phase of this turn. The Resolve Raid Orders step of the Action Phase is skipped this turn.",
    EVT_FEAST : "Feast for Crows",
    EVT_FEAST_TTIP : "Players may not place Consolidate Power order tokens during the Planning Phase of this turn.",
    EVT_FEAST_STATUS : "Players may not place Consolidate Power order tokens during the Planning Phase of this turn. The Resolve Consolidate Power Orders step of the Action Phase is skipped this turn.",
    EVT_RAINS : "Rains of Autumn",
    EVT_RAINS_TTIP : "Footmen do not provide combat strength to an adjacent battle while supporting this turn.",
    // EVT_RAINS_STATUS : "",
    // DECK 1 Second Edition
    EVT_BLADES : "A Throne of Blades",
    EVT_BLADES_TTIP : "The Holder of the Iron Throne may choose: a) everyone updates their Supply then reconciles armies, b) everyone musters units, or c) this card has no effect.",
    EVT_BLADES_STATUS : "The Holder of the Iron Throne may choose:<br>a) everyone updates their Supply then reconciles armies,<br>b) everyone musters units,<br>c) this card has no effect.",
    // DECK 2 Second Edition
    EVT_WINGS : "Dark Wings, Dark Words",
    EVT_WINGS_TTIP : "The holder of the Messenger Raven chooses whether a) everyone bids on the three influence tracks, b) everyone collects one Power token for every power icon present in areas they control, or c) this card has no effect.",
    EVT_WINGS_STATUS : "The holder of the Messenger Raven chooses whether<br>a) everyone bids on the three influence tracks,<br>b) everyone collects one Power token for every power icon present in areas they control,<br>c) this card has no effect.",
    // DECK 3 Second Edition
    EVT_RAINS2 : "Rains of Autumn",
    EVT_RAINS2_TTIP : "Players may not place March +1 order tokens during the Planning Phase of this turn.",
    EVT_LIES : "Web of Lies",
    EVT_LIES_TTIP : "Players may not place Support order tokens during the Planning Phase of this turn.",
    EVT_SWORD : "Put to the Sword",
    EVT_SWORD_TTIP : "The holder of the Valyrian Steel Blade chooses one of the following conditions for this Planning Phase: a) Defense Orders cannot be played, b) March +1 Orders cannot be played, or c) no restrictions.",
    EVT_SWORD_STATUS : "The holder of the Valyrian Steel Blade chooses one of the following conditions for this Planning Phase:<br>a) Defense Orders cannot be played,<br>b) March +1 Orders cannot be played,<br>c) no restrictions.",
    EVT_CHOICE_TEXT : "According to the current Westeros Card choose one event which should occur now!",
    EVT_CHOICE_C : "No effect",
    // PLANNING
    PLAN_STATUS : "Click on land or sea areas to set your orders.<br />Click on a placed order token to remove it.",
    PLAN_PROCEED : "Press the 'Proceed' button to continue.",
    PLAN_STATUS0 : "You are not able to set any orders. You have no units left.",
    PLAN_STATUS1 : "You have set your orders. All orders will be revealed simultaneously.",
    PLAN_STATUS_SPEC : "Players have to set their orders.",
    PLAN_DLG_SET_ORDER : "awaiting your orders...",
    PLAN_DLG_SELECT_ORDER : "Select the order you want to use.",
    PLAN_DLG_CLOSE : "click to close",
    PLAN_NO_SPECIAL : "Your position on the King's Court track is too low to use special orders.",
    PLAN_ORDER_NO_EFFECT : "Be aware that this order doesn't take effect on sea areas!",
    PLAN_ORDER_LIMIT : "Special order limit already reached.",
    PLAN_SET_ORDERS : "Set your Orders!",
    // RAVEN
    RAVEN_STATUS : "All orders are revealed.",
    RAVEN_STATUS1 : "You have got the Messenger Raven token!",
    RAVEN_STATUS2 : "You may swap one of your set orders by one of your unsused orders.",
    RAVEN_STATUS_SPEC : "Messenger Raven can be used.",
    RAVEN_STATUS_WAITING : "Waiting for player with the Messenger Raven...",
    RAVEN_ORDER_SWAP : "You may only swap a unit's order with an unused order.",
    RAVEN_ORDER_RESET : "Your Order Tokens have been reset.\nYou may only change one of your orders.",
    // RAID
    RAID_STATUS : "Select one of your Raid orders and then the order of an adjacent area you want to remove.<br />Click twice on your order to remove it.",
    RAID_ACTION : "You have to use a Raid order or remove one!",
    // MARCH
    MARCH_STATUS : "Select one of your March orders to activate your units. Select one or more units and click to an adjacent area to move selected units.<br />Click twice to remove a March order.",
    MARCH_ACTION : "You have to resolve a March order first!",
    MARCH_AREA_CONTROL : "KEEP CONTROL",
    MARCH_NO_POWER : "OUT OF POWER",
    MARCH_NO_POWER_TXT : "Be aware that you're going to give up your control over '{0}'!",
    MARCH_POWER : "Answer the 'Power Token' question first!",
    MARCH_PORT : "Order refused!\n\nYou are only allowed to move into a port which you control.", // -> into ports you control.
    MARCH_SUPPLY : "March not possible.\nYour Supply Level is too low!",
    MARCH_SUPPLY_ATTACK : "Attack not possible!\nYour Supply Level would be too low.",
    MARCH_WEAKLING : "You're not able to capture this area.\nYour combat strength is too low.",
    MARCH_TTIP_STR : "Your combat strength",
    MARCH_TTIP_STR_E : "Enemy's combat strength",
    MARCH_TTIP_SUPPORT : "Neutral support possible!",
    // BATTLE
    BATTLE_TITLE_FLAG : "Marks area with attacking units",
    BATTLE_TITLE_AREA : "Marks area where battle takes place",
    BATTLE_SUPPORT_STATUS : "Participants call for support",
    BATTLE_SUPPORT_STATUS1 : "You are able to support this battle. Choose!",
    BATTLE_SUPPORT_SELECT : "You need to choose who you will support!",
    BATTLE_SUPPORT_DEFAULT : "Stay neutral",
    BATTLE_SUPPORT_STATUS_SPEC : "Neutral players can support one of both participants.",
    BATTLE_SUPPORT_WAITING : "Waiting for neutral support...",
    BATTLE_CARD_STATUS : "Choosing House Cards",
    BATTLE_CARD_STATUS1 : "Participants of this battle have to select one House Leader. Cards will be revealed simultaneously.",
    BATTLE_CARDS_STATUS1 : "Participants of this battle have to select 3 House Cards. One of them will be randomly picked by the system.",
    BATTLE_CARD_STATUS2 : "For selection click on one of your available House Cards and then the 'Proceed' button to submit.",
    BATTLE_CARD_STATUS0 : "Your house card will be drawn automatically.",
    BATTLE_CARD_WAITING : "Waiting for revealing House Cards...",
    BATTLE_CARD_TEXT_ABILITY : "Text ability of {0}'s House Card can be used.",
    BATTLE_CARD_ABILITY_TITLE : "Using Your House Card",
    BATTLE_CARDS_CHOSEN : "Resolved Cards",
    BATTLE_BLADE_STATUS : "Valyrian Steel Blade may be used.",
    BATTLE_RESULT : "Battle Result",
    BATTLE_RESULT_STATUS : "Loser has to withdraw his defeated units.",
    BATTLE_PORT_TAKEOVER : "You might not be able to take over all enemy units!\nReason: Not enough available ships or your Supply Level is too low",
    BATTLE_HOUSE_CARD : "You have to choose one of your House Cards first!",
    BATTLE_3HOUSE_CARDS : "You have to select 3 House Cards!",
    BATTLE_PT_GAIN : "You gained {0} power tokens extra.",
    BATTLE_PT_GAIN_NAME : "{0} gained {1} power tokens extra.",
    BATTLE_KILLED : "Units were killed",
    BATTLE_UNITS_LIST : "{0} Footmen and {1} Knights",
    BATTLE_UNITS_LIST2 : "{0} Footmen,\n{1} Knights and\n{2} Siege Engines",
    BATTLE_NO_POWER : "You have no Power Tokens to use this special ability!",
    BATTLE_NO_RETREAT : "No available areas for withdrawal.\nAll your units have been killed!",
    BATTLE_RETREAT : "You have to withdraw your defeated units first!",
    BATTLE_RETREAT2 : "You have to withdraw your opponent's units first!",
    BATTLE_RETREAT_SPEC : "Loser has to withdraw his units.",
    BATTLE_RETREAT_CHOOSE : "Choose an area for your withdrawal!",
    BATTLE_RETREAT_FORCE : "You had to withdraw to '{0}'",
    BATTLE_RETREAT_SUPPLY : "Your Supply level is too low.\nYou're going to lose units after your withdrawal!",
    BATTLE_RETREAT_SUPPLY2 : "Your opponent's Supply level is too low.\nSome units will be lost after withdrawing!",
    BATTLE_CARD1 : "House Card",
    BATTLE_CARD2 : "You have to resolve your house card's text ability:",
    BATTLE_CARD3 : "Player has to resolve his house card's text ability:",
    BATTLE_CARD_B1 : "If you win this battle, you may expend one Power Token to choose and discard one House Card from the losing player's hand.",
    BATTLE_CARD_B6 : "If you win this battle, you may upgrade one of your Footmen to a Knight. That Footmen must have participated in the battle as either attacker or defender.",
    BATTLE_CARD_L1 : "If you win this battle, remove any one of the losing opponent\'s Order tokens from the board.",
    BATTLE_CARD_S1 : "If you win this battle, you may return one of your discarded House Cards to your hand.",
    BATTLE_CARD_G6 : "If you win this battle, you may immediately remove a Support or Consolidate Power order in any Sea or Land area adjacent to the battle.",
    BATTLE_CARD_M2 : "If you win this battle, you may steal any one Influence Token (Iron Throne, Valyrian Steel Blade or Messenger Raven) held by your opponent and use its ability until the next 'Clash of Kings' resolution.",
    BATTLE_CARD2_B1 : "After combat, you may look at your opponent's hand and discard one card of your choice.",
    BATTLE_CARD2_B6 : "If you win this combat, you may upgrade one of your participating Footmen (or one supporting Baratheon Footmen) to a Knight.",
    BATTLE_CARD_OLENNA : "Action 'Proceed' not possible!\nYou didn't remove any of your opponent's orders yet.",
    BATTLE_STEELBLADE : "VALYRIAN STEELBLADE", // Not sure where this is used, does it have to be in caps?
    BATTLE_STR_TITLE : "Battle for '{0}'",
    BATTLE_STR_BASE : "Combat Strength",
    BATTLE_STR_TOB : "Tides Of Battle",
    BATTLE_STR_SUPPORT_LAND : "Support Land",
    BATTLE_STR_SUPPORT_SEA : "Support Sea",
    BATTLE_STR_SUPPORT_NEUTRAL : "Neutral Support",
    BATTLE_STR_TOTAL : "Total",
    BATTLE_RESULT_WIN : "You won!",
    BATTLE_RESULT_LOSE : "You lost!",
    BATTLE_RESULT_SPEC : "{0} defeated {1}!",
    // CONSOLIDATE POWER
    CP_STATUS : "Your orders will be resolved automatically if you do not have any special CP orders.<br />Remove one order token to consolidate power. To muster units select the special CP order and recruit units on the highlighted areas.",
    CP_ACTION : "You have to resolve one of your Consolidate Power Orders first!",
    // CONFIRMATIONS
    CNFM_ATTACK : "You are going to attack '{0}' from '{1}' with\n{2}!\n\nClick OK to proceed.",
    CNFM_BLADE : "Do you want to use the Valyrian Steel Blade<br />to increase your combat strength?",
    CNFM_BLADE_TOB : "Do you want to use the Valyrian Steel Blade<br />to replace your Tides Of Battle card?",
    CNFM_TEXT_ABILITY : "Do you want to use your House Card's text ability?",
    CNFM_INVEST_PT : "Do you want to invest one Power Token to keep control of '{0}'?",
    CNFM_USABLE_ORDERS : "WARNING:\nYou didn't assign orders to all of your units. You have placed {0} Order Tokens so far.\nDo you really want to proceed?",
    CNFM_NO_RAVEN : "WARNING:\nAre you sure you do NOT want to use the messenger raven?",
    CNFM_NO_ORDERS : "WARNING:\nNo orders for your units selected!\nDo you really want to proceed?",
    CNFM_NO_ORDERS2 : "Are you really REALLY sure that you do NOT want to\nset orders for your troops?",
    CNFM_NO_ENEMY_CARD : "You didn't choose one of your opponent's house cards.\nAre you sure to proceed?",
    CNFM_NO_UPGRADE : "You didn't upgrade one of you footmen.\nDo you really want to proceed?",
    CNFM_NO_ENEMY_ORDER : "You didn't remove one of your enemy's Order Tokens!\nDo you really want to proceed?",
    CNFM_NO_CARD : "You didn't choose one of your House Cards!\nDo you really want to proceed?",
    CNFM_NO_BLADE : "Are you really sure you do NOT want to USE the Valyrian Steel Blade?", //Not sure if too long now? 'Steelblade' to 'Valyrian Steel Blade'
    CNFM_NO_TEXT_ABILITY : "Are you really sure you do NOT want to USE your House Card's text ability?",
    CNFM_NO_NEW_UNITS : "You didn't recruit any new units.\nDo you really want to proceed?",
    CNFM_NO_BID : "Do you really want to bid 0 power tokens?",
    CNFM_NOT_ALL_MP : "You didn't use up all available Mustering Points.\nDo you want to proceed anyway?",
    CNFM_PBEM_SWITCH : "Are you really sure to abort this LIVE game?",
    CNFM_PORT_TAKEOVER_EASY : "Do you want to take over the port's ships?",
    CNFM_PORT_TAKEOVER : "You are attacking an area with a port.\nIf you win this battle, do you want to take over the port's ships?",
    CNFM_USE_PT : "Are you sure you want to expend one of your power tokens\nto remove your enemy's house card?",
    // GAME OVER
    GAME_OVER_DEFEAT : "YOU HAVE BEEN DEFEATED!",
    GAME_OVER_TXT : "House {0} conquered the Iron Throne successfully by your wise leadership.", //Not sure if by should be through
    GAME_OVER_TXT_NAME : "House {0} conquered the Iron Throne successfully by its commander {1}.",
    GAME_OVER_VICTORY : "{0} was victorious!",
    GAME_OVER_WIN : "YOU WERE VICTORIOUS!",
    // DONE.
    format : function (str, values) {
        for (var i = 0; i < values.length; i++) {
            var needle = "{" + i + "}"; // {0} .. {n}
            if (str.indexOf(needle) >= 0) {
                str = str.replace(new RegExp("\\{" + i + "\\}", "g"), values[i]);
            }
        }
        return str
    }
};